### Assignment 1 - Gavin Wainwright

In [88]:
import numpy as np

Question 1

In [89]:
x = np.array([[2], [2], [6]])
X = np.array([[-4,7,5], [1,-9,2], [8,3,6]])
Y = np.array([[2,4,6], [1,0,13], [-4,5,5]])
Z = np.array([[4,-1,0], [1,1,1]])

In [90]:
# x^TXY
x.T.dot(X).dot(Y)

array([[-102,  418,  684]])

In [91]:
# YX
Y.dot(X)

array([[ 44,  -4,  54],
       [100,  46,  83],
       [ 61, -58,  20]])

In [92]:
# 2X + 2Y + X^TY
(2 * X) + (2 * Y) + (X.T.dot(Y))

array([[-43,  46,  51],
       [ -3,  25, -30],
       [ -4,  66, 108]])

In [93]:
# YZ^T
Y.dot(Z.T)

array([[  4,  12],
       [  4,  14],
       [-21,   6]])

In [94]:
# Z^TZx
Z.T.dot(Z.dot(x))

array([[34],
       [ 4],
       [10]])

Question 2

In [95]:
# Create two matrices and two vectors
X = np.array([[2,3], [9,1]])
Y = np.array([[1,0], [2,1]])
x = np.array([[1], [3]])
y = np.array([[2], [4]])

In [96]:
# Write the code that extracts the 1st column of X
X[:, 0]

array([2, 9])

In [97]:
# Write the code that extracts the 2nd row of Y
Y[1, :]

array([2, 1])

In [98]:
# Write the code that extracts the bottom right value of X
X[1, 1]

1

In [99]:
# Write the code that adds X + Y
X + Y

array([[ 3,  3],
       [11,  2]])

In [100]:
# Write the code that performs X + YX
X + (Y.dot(X))

array([[ 4,  6],
       [22,  8]])

In [101]:
# Write the code that performs the Hadamard product x (*) y
x * y

array([[ 2],
       [12]])

In [102]:
# Write the code that performs the outer product x (x) y
np.outer(x, y)

array([[ 2,  4],
       [ 6, 12]])

In [103]:
# Write the code that performs the dot product XY
X.dot(Y)

array([[ 8,  3],
       [11,  1]])

In [104]:
# Write the code that performs the inner product <X, Y>
X.dot(Y)

array([[ 8,  3],
       [11,  1]])

Question 3

In [105]:
import autograd.numpy as np
from autograd.numpy import log
from autograd.numpy import exp
from autograd import grad

In [106]:
x1 = np.array([[1], [0]])
x2 = np.array([[2], [1]])
x = np.array([[1], [2]])
y = np.array([[2], [0]])
w = np.array([[2], [0]])
A = np.array([[1, 0], [0, 2]])
one = np.array([[1], [1]])

In [107]:
# Part 1
def f(x):
    return x.T @ A @ x - x.T @ y

def f_prime(x):
    return 2 * A @ x - y

auto_grad = grad(f)
x = np.array([[1], [1]])
print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[0]
 [4]]
Mine: [[0]
 [4]]


In [108]:
# Part 2
def f(x):
    return x.T @ A @ one

def f_prime(x):
    return A @ one

auto_grad = grad(f)
x = np.array([[1], [1]])
print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[1]
 [2]]
Mine: [[1]
 [2]]


In [109]:
# Part 3
def f(x):
    return x.T @ one

def f_prime(x):
    return one

auto_grad = grad(f)
x = np.array([[1], [1]])
print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[1]
 [1]]
Mine: [[1]
 [1]]


In [110]:
# Part 4
x = [x1, x2]

def f(w):
    return sum(w.T @ xi for xi in x)

def f_prime(w):
    return sum(x)

auto_grad = grad(f)
w = np.array([[1], [1]])
print(f'Auto: {auto_grad(w)}\nMine: {f_prime(w)}')

Auto: [[3]
 [1]]
Mine: [[3]
 [1]]


Question 4

In [111]:
# Part 1 - Linear
def f(x):
    return y.T @ x

def f_prime(x):
    return y

auto_grad = grad(f)

x = np.random.randn(2, 1)
y = np.random.randn(2, 1)

print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[0.23225043]
 [0.5207804 ]]
Mine: [[0.23225043]
 [0.5207804 ]]


In [112]:
# Part 2 - Quadratic
def f(x):
    return x.T @ A @ x

def f_prime(x):
    return (A + A.T) @ x

auto_grad = grad(f)
x = np.random.randn(2, 1)
A = np.random.randn(2, 2)
print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[-2.18061576]
 [-1.32073189]]
Mine: [[-2.18061576]
 [-1.32073189]]


In [113]:
# Part 3 - Trace of Quadratic
def f(x):
    return np.trace(x.T @ A @ x)

def f_prime(x):
    return (A + A.T) @ x

auto_grad = grad(f)
x = np.random.randn(2, 1)
A = np.random.randn(2, 2)
print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[-2.29167572]
 [-1.967058  ]]
Mine: [[-2.29167572]
 [-1.967058  ]]


In [114]:
# Part 4 - ReLU
def f(w, x):
    v = np.dot(np.transpose(w), x)
    return np.maximum(0, v)

def f_prime(w, x):
    if w.T.dot(x) > 0:
        return x
    else:
        return 0

auto_grad = grad(f)
w = np.random.randn(2, 1)
x = np.random.randn(2, 1)
print(f'Auto: {auto_grad(w, x)}\nMine: {f_prime(w, x)}')

Auto: [[0.]
 [0.]]
Mine: 0


In [115]:
# Part 5 - Linear Regression
def f(w):
    return 0.5 * np.sum([(w.T @ x[i] - y[i])**2 for i in range(n)])

def f_prime(w):
    return np.sum([(w.T @ x[i] - y[i]) * x[i] for i in range(n)], axis=0)

auto_grad = grad(f)

n, d = 10, 5
x = np.random.randn(n, d)
y = np.random.randn(n, 1)
w = np.random.randn(d, 1)

print(f'Auto: {auto_grad(w).flatten()}\nMine: {f_prime(w)}')

Auto: [  5.55445045 -11.93219575   2.14850922   0.37441412  -4.05223329]
Mine: [  5.55445045 -11.93219575   2.14850922   0.37441412  -4.05223329]


In [116]:
# Part 6 - Multivariate Gaussian Trace
def f(x, A):
    return np.exp(-np.trace(x.T @ A @ x))

def f_prime(x, A):
    return -np.exp(-x.T @ A @ x) * (A + A.T) @ x

auto_grad = grad(f)

d = 3
x = np.random.randn(d, 1)
A = np.random.randn(d, d)

print(f'Auto: {auto_grad(x, A)}\nMine: {f_prime(x, A)}')

Auto: [[-59.41861153]
 [ -2.62179167]
 [-84.90240021]]
Mine: [[-59.41861153]
 [ -2.62179167]
 [-84.90240021]]


In [117]:
# Part 7 - Multivariate Gaussian
def f(x, A):
    return np.exp(-x.T @ A @ x)

def f_prime(x, A):
    return -np.exp(-x.T @ A @ x) * (A + A.T) @ x

auto_grad = grad(f)

d = 3
x = np.random.randn(d, 1)
A = np.random.randn(d, d)

print(f'Auto: {auto_grad(x, A)}\nMine: {f_prime(x, A)}')

Auto: [[-0.72813839]
 [ 0.3378244 ]
 [-0.55730784]]
Mine: [[-0.72813839]
 [ 0.3378244 ]
 [-0.55730784]]


In [118]:
# Part 8 - Sigmoid
def f(z):
    return 1 / (1 + np.exp(-z))

def f_prime(z):
    fz = f(z)
    return fz * (1 - fz)

auto_grad = grad(f)

z = np.random.randn()

print(f'Auto: {auto_grad(z)}\nMine: {f_prime(z)}')

Auto: 0.24745098523761763
Mine: 0.2474509852376176


In [119]:
# Part 9 - Logistic Regression Objective
def f(w, x):
    return 1 / (1 + np.exp(-w.T @ x))

def f_prime(w, x):
    fw = f(w, x)
    return fw * (1 - fw) * x

auto_grad = grad(f)

d = 3
w = np.random.randn(d, 1)
x = np.random.randn(d, 1)

print(f'Auto: {auto_grad(w, x)}\nMine: {f_prime(w, x)}')

Auto: [[-0.13190646]
 [ 0.16317177]
 [ 0.03648653]]
Mine: [[-0.13190646]
 [ 0.16317177]
 [ 0.03648653]]


In [120]:
# Part 10 - L1 Norm
def f(x):
    return np.sum(np.abs(x))

def f_prime(x):
    return np.sign(x)

auto_grad = grad(f)

x = np.random.randn(3, 1)

print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[ 1.]
 [-1.]
 [-1.]]
Mine: [[ 1.]
 [-1.]
 [-1.]]


In [121]:
# Part 11 - L2 Norm
def f(x):
    return np.sqrt(np.sum(x**2))

def f_prime(x):
    norm_x = np.sqrt(np.sum(x**2))
    if norm_x == 0:
        return np.zeros_like(x)
    else:
        return x / norm_x

auto_grad = grad(f)

x = np.random.randn(3, 1)

print(f'Auto: {auto_grad(x)}\nMine: {f_prime(x)}')

Auto: [[0.79391072]
 [0.32206084]
 [0.51573499]]
Mine: [[0.79391072]
 [0.32206084]
 [0.51573499]]


In [122]:
# Part 12 - SVM Objective

# instructions stated to skip

In [123]:
# Part 13 - PCA Objective
def f(x, A, λ):
    return x.T @ A @ x - λ * (x.T @ x - 1)

def f_prime(x, A, λ):
    return (A + A.T) @ x - 2 * λ * x

auto_grad = grad(f)

d = 3
x = np.random.randn(d, 1)
A = np.random.randn(d, d)
λ = np.random.randn()

print(f'Auto: {auto_grad(x, A, λ)}\nMine: {f_prime(x, A, λ)}')

Auto: [[-0.19338511]
 [ 0.02452567]
 [-0.9177349 ]]
Mine: [[-0.19338511]
 [ 0.02452567]
 [-0.9177349 ]]


In [124]:
# Part 14 - Gaussian Maximum Likelihood
def f(µ, x, σ):
    n = len(x)
    return -n * np.log(np.sqrt(2 * np.pi) * σ) - (1/(2 * σ**2)) * np.sum((x - µ)**2)

def f_prime(µ, x, σ):
    return (1/(σ**2)) * np.sum(x - µ)

auto_grad = grad(f)

µ = np.random.randn()
σ = np.random.rand()
x = np.random.randn(10, 1)

print(f'Auto: {auto_grad(µ, x, σ)}\nMine: {f_prime(µ, x, σ)}')

Auto: 4.510568828136615
Mine: 4.510568828136615


In [125]:
# Part 15 - Exponential Maximum Likelihood
def f(λ, x):
    n = len(x)
    return np.sum(np.log(λ) - λ * x)

def f_prime(λ, x):
    n = len(x)
    return n / λ - np.sum(x)

auto_grad = grad(f)

λ = np.random.randn()
x = np.random.randn(10, 1)

print(f'Auto: {auto_grad(λ, x)}\nMine: {f_prime(λ, x)}')

Auto: 11.479169190074714
Mine: 11.479169190074714


In [126]:
# Part 16 - Bernoulli Maximum Likelihood
def f(p, α):
    return np.sum(α * np.log(p) + (1 - α) * np.log(1 - p))

def f_prime(p, α):
    return np.sum(α / p - (1 - α) / (1 - p))

auto_grad = grad(f)

p = np.random.randn()
α = np.random.randint(0, 2, 10)

print(f'Auto: {auto_grad(p, α)}\nMine: {f_prime(p, α)}')

Auto: 63.51224451385266
Mine: 63.51224451385265


In [128]:
# Part 17 - Uniform Maximum Likelihood
def f(v):
    a, b = v
    if b <= a:
        return np.inf
    n = 10
    return n * np.log(1 / (b - a))

def f_prime(v):
    a, b = v
    if b <= a:
        return [np.inf, np.inf]
    n = 10
    common_term = n / (b - a)
    return [common_term, -common_term]

auto_grad = grad(f)

a = np.random.randn()
b = a + np.random.randn()
v = np.array([a, b])

print(f'Auto: {auto_grad(v)}\nMine: {f_prime(v)}')

Auto: [ 6.3301155 -6.3301155]
Mine: [6.330115502432898, -6.330115502432898]
